version: 2

models:
  - name: jail_population_total
    description: Monthly totals for jail populations report
    columns:
    - name: report_date
    - name: pretrial_felons
    - name: convicted_felons
    - name: convicted_felons_sentenced_county
    - name: parole_violators
    - name: parole_violators_new_charge
    - name: pretrial_misdemeanor
    - name: convicted_misdemeanor
    - name: bench_warrants
    - name: federal
    - name: pretrial_sjf
    - name: convicted_sjf_sentenced_county
    - name: convicted_sjf_sentenced_state
    - name: total_others
    - name: total_local
    - name: total_contract
    - name: total_population
    - name: total_capacity
    - name: pct_capacity
    - name: available_beds
    - name: processed_at

  - name: jail_population_county
    description: County-level monthly count for jail populations report
    columns:
    - name: county_name
    - name: p_code
    - name: report_date
    - name: pretrial_felons
    - name: convicted_felons
    - name: convicted_felons_sentenced_county
    - name: parole_violators
    - name: parole_violators_new_charge
    - name: pretrial_misdemeanor
    - name: convicted_misdemeanor
    - name: bench_warrants
    - name: federal
    - name: pretrial_sjf
    - name: convicted_sjf_sentenced_county
    - name: convicted_sjf_sentenced_state
    - name: total_others
    - name: total_local
    - name: total_contract
    - name: total_population
    - name: total_capacity
    - name: pct_capacity
    - name: available_beds
    - name: processed_at

  - name: pregnancy_base
    description: Base table to convert side-by-side columns into long columns; this is the first step before it can be split into total/county counts
    columns:
    - name: county_name
    - name: pregnant_female_count
    - name: processed_at
    - name: report_date

  - name: pregnancy_county
    description: Monthly pregnant inmate counts by county
    columns:
    - name: county_name
    - name: p_code
    - name: pregnant_female_count
    - name: processed_at
    - name: report_date

  - name: pregnancy_total
    description: State-level pregnant inmate count by month
    columns:
    - name: pregnant_female_count
    - name: processed_at
    - name: report_date

  - name: immigrant_data_date
    description: Intermediate table to retrieve report date from parsed document
    columns:
    - name: data_date
      description: The date printed on the top of the report (sometimes different from date path saved under)
    - name: processed_at
    - name: report_date

  - name: immigrant_county
    description: County-level counts of detained immigrants by month
    columns:
    - name: county_name
    - name: p_code
    - name: inmate_count
    - name: inmate_days
    - name: cost
    - name: processed_at
    - name: report_date
    - name: data_date
      description: The date printed on the top of the report (sometimes different from date path saved under)

  - name: immigrant_total
    description: State-level counts of detained immigrants by month
    columns:
    - name: inmate_count
    - name: inmate_days
    - name: cost
    - name: processed_at
    - name: report_date
    - name: data_date
      description: The date printed on the top of the report (sometimes different from date path saved under)

  - name: serious_incidents_data_date
    description: Intermediate table to retrieve report date from parsed document
    columns:
    - name: data_date
      description: The date printed on the top of the report (sometimes different from date path saved under)
    - name: processed_at

  - name: serious_incidents_county
    description: County-level counts of serious incidents by month
    columns:
    - name: county_name
    - name: p_code
    - name: suicide_count
    - name: attempted_suicide_count
    - name: death_in_custody_count
    - name: escape_count
    - name: assault_count
    - name: sexual_assault_count
    - name: serious_injury_count
      description: Serious bodily injury
    - name: use_of_force_count
      description: Incidents where use of force resulted in bodily injury
    - name: processed_at
    - name: data_date
      description: The date printed on the top of the report (sometimes different from date path saved under)

  - name: serious_incidents_total
    description: State-level counts of detained immigrants by month
    columns:
    - name: suicide_count
    - name: attempted_suicide_count
    - name: death_in_custody_count
    - name: escape_count
    - name: assault_count
    - name: sexual_assault_count
    - name: serious_injury_count
      description: Serious bodily injury
    - name: use_of_force_count
      description: Incidents where use of force resulted in bodily injury
    - name: processed_at
    - name: data_date
      description: The date printed on the top of the report (sometimes different from date path saved under)
