name: Data Scraping/Processing CLI CI

on: [push]

defaults:
  run:
    working-directory: extractor

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.8
      - name: View poetry
        run: poetry --help
      - name: Install Dependencies
        run: poetry install
      - name: Code Quality
        run: poetry run black . --check
      - name: Run Tests/Coverage
        # run: poetry run pytest --cov . --cov-config=.coveragerc -n 2
        run: poetry run extract --help
